
---
title: "schoolbuses - main"
author: "Gabriel Florit"
output:
  html_document:
    self_contained: false
---

```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)
library(scales)
library(reshape2)
library(lubridate)
setwd("~/Documents/dev/schoolbuses/data")
```

```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=TRUE}
rawdata <- read.table('input/SY1314_AM_Bus_Data_for_the_Globe.txt', sep='\t', header=TRUE)
```

### Data analysis

****
```{r, results='asis', fig.width=10, fig.height=3, warning=FALSE, message=FALSE}
data.days <- rawdata %>%
  filter(
    errortype == '',
    !is.na(bell_late),
    !is.na(sched_late),
    !is.na(belltime),
    !is.na(ActualArrivalTime)
  ) %>%
  mutate(
    date = floor_date(dmy(date), 'day'),
    five_late = ((hm(ActualArrivalTime) - hm(belltime))/minutes(1) + 5),
    is.bell.late = bell_late > 0,
    is.five.late = five_late > 0,
    is.sched.late = sched_late > 0
  )

data.days %>%
  group_by(is.bell.late) %>%
  tally() %>%
  mutate(percent = n/sum(n)) %>%
  knitr::kable()

data.days %>%
  group_by(is.five.late) %>%
  tally() %>%
  mutate(percent = n/sum(n)) %>%
  knitr::kable()

data.days %>%
  group_by(is.sched.late) %>%
  tally() %>%
  mutate(percent = n/sum(n)) %>%
  knitr::kable()
```

****
Let's plot weekly tardiness by these three variables.
```{r, results='asis', fig.width=10, fig.height=3, warning=FALSE, message=FALSE}
bell.late <- data.days %>%
  group_by(date, is.bell.late) %>%
  tally() %>%
  group_by(date) %>%
  mutate(bell.late = n/sum(n)) %>%
  filter(is.bell.late) %>%
  select(-is.bell.late, -n)

five.late <- data.days %>%
  group_by(date, is.five.late) %>%
  tally() %>%
  group_by(date) %>%
  mutate(five.late = n/sum(n)) %>%
  filter(is.five.late) %>%
  select(-is.five.late, -n)

sched.late <- data.days %>%
  group_by(date, is.sched.late) %>%
  tally() %>%
  group_by(date) %>%
  mutate(sched.late = n/sum(n)) %>%
  filter(is.sched.late) %>%
  select(-is.sched.late, -n)

late <- bell.late %>%
  inner_join(five.late, by=c('date')) %>%
  inner_join(sched.late, by=c('date')) %>%
  melt(c('date'))

ggplot(late, aes(date, value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  ggtitle('Percent of tardy buses by various definitions of "late"') +
  scale_y_continuous(labels=percent) +
  theme(axis.title.y = element_blank()) +
  xlab('day')
```
